// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using employee.Models;

#nullable disable

namespace employee.Migrations
{
    [DbContext(typeof(RentSaaSContext))]
    [Migration("20250504192431_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("employee.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "MoazHamed123@example.com",
                            FirstName = "Moaz",
                            LastName = "Hamed",
                            Position = "Developer"
                        },
                        new
                        {
                            Id = 2,
                            Email = "DohaMedhat12@example.com",
                            FirstName = "Doha",
                            LastName = "Medhat",
                            Position = "Designer"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ShereenAhmed23@example.com",
                            FirstName = "Shereen",
                            LastName = "Ahmed",
                            Position = "Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
